spring:
  kafka:
    bootstrap-servers: 10.112.184.214:9092
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    username:
    password:
    url: jdbc:clickhouse://10.112.196.200:8123/default